version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: "Europe/Madrid"
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps
    groups:
      python-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "07:15"
      timezone: "Europe/Madrid"
    open-pull-requests-limit: 5
    commit-message:
      prefix: ci
    groups:
      actions-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
